[package]
name = "ashfall"
version = "1.0.0"
authors = []

[addresses]
ashfall = "0xaf6509a4df30480896f87d0b2b75bb7f698bbd95d3e22609edf158bf0b1e0f58"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
