[package]
name = "ashfall"
version = "1.0.0"
authors = []

[addresses]
ashfall = "0xf913a8d36a166d9a048b11eeaf902f71bdfba8c8931c351800b145f365f36c8e"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
